meta_name: "Le WaPong"
meta_title: "LeWapong - digital sports tournament organization"
meta_description: "Le WaPong is a tool that helps you organize tournaments with your friends in a simple and digital way. Le WaPong was developed in a two week project at Le Wagon in Lisbon (Batch 1041)."
meta_image: "meta_image.png"
